from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from datetime import datetime


def generate_pdf(df):

    filename = "DataNova_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    # ===========================
    # TITLE
    # ===========================

    title = Paragraph(
        "<font color='blue'><b>📊 DataNova AI Data Analyst Report</b></font>",
        styles["Title"]
    )

    elements.append(title)
    elements.append(Spacer(1, 0.3 * inch))

    # ===========================
    # DATE
    # ===========================

    date = Paragraph(
        f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y %I:%M %p')}",
        styles["Normal"]
    )

    elements.append(date)
    elements.append(Spacer(1, 0.2 * inch))

    # ===========================
    # SUMMARY TABLE
    # ===========================

    summary = [

        ["Metric", "Value"],

        ["Rows", str(df.shape[0])],

        ["Columns", str(df.shape[1])],

        ["Missing Values", str(df.isnull().sum().sum())],

        ["Duplicate Rows", str(df.duplicated().sum())]

    ]

    table = Table(summary)

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

        ("ALIGN", (0, 0), (-1, -1), "CENTER")

    ]))

    elements.append(table)

    elements.append(Spacer(1, 0.4 * inch))

    # ===========================
    # DATASET PREVIEW
    # ===========================

    elements.append(
        Paragraph("<b>Dataset Preview</b>", styles["Heading2"])
    )

    preview = [list(df.columns)]

    for row in df.head(5).values.tolist():

        preview.append([str(i) for i in row])

    preview_table = Table(preview)

    preview_table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),

        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

        ("ALIGN", (0, 0), (-1, -1), "CENTER")

    ]))

    elements.append(preview_table)

    elements.append(Spacer(1, 0.4 * inch))

    # ===========================
    # FOOTER
    # ===========================

    elements.append(

        Paragraph(

            "<font color='grey'>Generated by DataNova AI Data Analyst</font>",

            styles["Italic"]

        )

    )

    doc.build(elements)

    return filename